### ISSUE TITLE
import zodbpickle.pickle  UnicodeDecodeError

### ISSUE THREAD

**Issue by aidiss** [zopefoundation/zodbpickle#20]
```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-33-82dc2cbee6e8> in <module>()
----> 1 import zodbpickle.pickle

C:\Users\user\Miniconda3\lib\site-packages\zodbpickle\pickle.py in <module>()
      2 
      3 if sys.version_info[0] >= 3:
----> 4     from .pickle_3 import *
      5 else:
      6     from .pickle_2 import *

C:\Users\user\Miniconda3\lib\site-packages\zodbpickle\pickle_3.py in <module>()
   1481 # Use the faster _pickle if possible
   1482 try:
-> 1483     from zodbpickle._pickle import *
   1484 except ImportError:
   1485     Pickler, Unpickler = _Pickler, _Unpickler

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 4: invalid start byte
```

**Comment by jamadden** [comment]
What are the details about your Python installation (exact version, platform tag)? 

How did you install zodbpickle? via pip? Did it compile from source or choose the egg or exe installer?

If you're not sure, try creating a new virtual environment and running it's `pip install -v zodbpickle`. If that still fails, try (after uninstalling zodbpickle, or in a new venv) `pip install -v --no-binary :all: zodbpickle`. The logs from those cases could be useful.

**Comment by aidiss** [comment]
Python 3.4.4 |Anaconda 2.1.0 (64-bit)| (default, Feb 16 2016, 09:54:04) [MSC v.1
600 64 bit (AMD64)] on win32

I installed ZODB by pip install zodb
I will try creating a new virtual environment later and get bet with more details

**Comment by jamadden** [comment]
Are there any updates on this?

**Comment by tseaver** [comment]
I cannot see any way for the import of `zodbpickle._pickle` to raise a `UnicodeDecdeError`, unless somehow the C files were transcoded to a non-UTF8 encoding during save?

The module initialization doesn't touch anything Unicode related:  it initializes its types and exceptions, and sets them into its dictionary using ASCII names.

@aidiss Please reopen if you can supply any further information.
