### ISSUE TITLE
Create more wheels

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zodbpickle#32]
Currently there is only ~~an sdist~~ the sdist and win wheels on PyPI. Having more wheels there would be nice.

**Comment by mgedmin** [comment]
We can steal zope.interface's .travis.yml and appveyor.yml.  IIRC there's nothing specific to zope.interface in there.

https://github.com/zopefoundation/zope.security/issues/46 has a checklist for Windows wheels.  Do you also want manylinux and/or Mac OS wheels?

**Comment by mgedmin** [comment]
Never mind; I see zodbpickle already has Windows wheels.  What remains is taking manylinux bits from zope.interface's .travis.yml and perhaps generating a new secret for this repository (Travis encryption of the zope.wheelbuilder PyPI password is valid for a repository, whereas Appveyor's encryption is for a user account).

**Comment by mgedmin** [comment]
Here's the Travis secret for zodbpickle:
```
secure: "edbJQIhe7grjaug7dxExoyB0zkrLca5IphzuQd2IfjGjBCY6Dn+QEBtDOMOcPjUsSvgxWL2XG2ZGIFF33bsoFlq0bZFPMtv5ZQ6jcpYQEpPX61fHsNzPs2RXavpHgHFC4aXt1o7jH7aSeImV98WWsNZTL5rhW4aHbgOM/jnnWdc="
```

**Comment by mgedmin** [comment]
In addition to zope.interface's `.travis.yml` you'll want `.manylinux.sh` and `.manylinux-install.sh`, and you'll want to `s/zope.interface/zodbpickle/` in the latter.

**Comment by icemac** [comment]
@mgedmin Thank you for your advice and sorry for being not patient enough to see the windows wheels which got created via AppVeyor.
