### ISSUE TITLE
Possible discrepency in Unpickler.noload_obj()

### ISSUE THREAD

**Issue by moreati** [zopefoundation/zodbpickle#41]
`Unpickler.noload_obj()` does not append a `None` to the stack. This appears to be inconsistent with `noload_inst()` et al, which do - in order to substitute for an instantiated object.

Like #40 I'm not sure if this is a very obscure or a misunderstanding on my part. I'll investigate further.

**Comment by tseaver** [comment]
@moreati Thanks for the report!

I was just digging through the C code today, in preparation for modernizing our fork from the Python3 stdlib version (currently based on the Python 3.3 module).

Note that the last line of the `noload_obj` method clears the stack *above* the marker (that is the `i+1`), leaving what would have been the `cls` object in place:
```
static int
noload_obj(UnpicklerObject *self)
{
    int i;


    if ((i = marker(self)) < 0) return -1;
    return Pdata_clear(self->stack, i+1);
}
```
Given how we use the `noload` variants, it doesn't really matter that the top-of-stack is a class vs. `None`.
