### ISSUE TITLE
RFC: CPython 3.8.0b1 stdlib pickle.py depends on C _pickle module

### ISSUE THREAD

**Issue by moreati** [zopefoundation/zodbpickle#48]
I'd like to draw your attention to https://bugs.python.org/issue37210, in case you wish to express an interest. In CPython 3.8.0b1 the pure Python version of the `pickle` module is no longer independent of the C `_pickle` module. The former imports `PickleBuffer` from the later, and is essential to implementing Pickle protocol 5.

Although bpo-37210 was opened at my behest I'm proposing to close it as WONTFIX.

Should you have no preference, then sorry for the noise and feel free to close this ticket without comment.

**Comment by mgedmin** [comment]
I don't think `pickle` depending on `_pickle` causes us any problems?

(We could add `3.8-dev` to .travis-ci.yml and make sure.)

**Comment by icemac** [comment]
`3.8-dev` on TravisCI is green so closing this issue here.
