### ISSUE TITLE
Can zodbpickle be forced to use dill? Currently it can't serialize custom classes like dill

### ISSUE THREAD

**Issue by radiantone** [zopefoundation/zodbpickle#72]
Can zodbpickle be forced to use dill? Currently it can't serialize custom classes like dill

**Comment by d-maurer** [comment]
Darren Govoni wrote at 2022-8-28 04:58 -0700:
>Can zodbpickle be forced to use dill? Currently it can't serialize custom classes like dill

Likely.

There are several pickle extension mechanisms.
Read the associated Python documentation.

**Comment by agroszer** [comment]
Why do you need zodbpickle? You have a DB that needs simultaneous access from py2.7 and py3.x clients?

**Comment by radiantone** [comment]
Because a package I use uses it

**Comment by icemac** [comment]
I am closing this old issue. Feel free to re-open it if there are any news about the topic.
