### ISSUE TITLE
RFE: please prepare test suite to be able use it with pytest as well

### ISSUE THREAD

**Issue by kloczek** [zopefoundation/zodbpickle#85]
As we discussed in #70 I've pointed that currently test suite is not ready to be used with pytest.
Part of the issue is that is pytest scans only test* files so to even asses how much of the test suite needs to be adapted to be able use it with pytest as well some files needs to be renamed.

At the end of our conversation you mention that it takes time to work.
If you want I can try to prepare PR adding necessary adaptations.

**Comment by icemac** [comment]
Feel free to try it out to port this package to pytest.
I think it is possible, but I see more pressing maintainance issues for me as maintainer.

**Comment by kloczek** [comment]
OK so you wanto me to prepare PR with seto of renames? 🤔

**Comment by icemac** [comment]
What do you mean by `seto of renames`?

**Comment by kloczek** [comment]
As I wrote pytest scans only test*.py files so to be a scannable test suite files should be wit hat kind of names.

**Comment by dataflake** [comment]
`pytest` support is not planned. Please use `zope.testrunner`.
